### ISSUE TITLE
Travis - add integration tests with Elasticsearch instance

### ISSUE THREAD

**Issue by macbre** [macbre/wikia-common-kibana#9]
* https://www.peterbe.com/plog/elasticsearch-5-in-travis-ci
* https://docs.travis-ci.com/user/database-setup/#elasticsearch

https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.5.1.tar.gz (33 MB)

```yaml
env:
  - ES_VERSION=5.1.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
```

Auto-installed version:

```
ElasticSearch version
5.5.0
```
